### PR TITLE
Attempt to Fix #102

### LINKED ISSUE #102: Sha3 bypass panic
`cli --sha3-bypass --work-dir /bsc/0x9bd7cd81B1dDd0f5F0c77A22f541AF24653aD129  -c BSC --onchain --onchain-block-number 29625908 -f --target 0x9bd7cd81B1dDd0f5F0c77A22f541AF24653aD129`

gives:

`thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 18446744073709551615', /ityfuzz/src/evm/middlewares/sha3_bypass.rs:216:39`

I guess it has connection to heimdall decompilation.

When running this without sha3-bypass, execution ends with:

`memory allocation of 54043195528446112 bytes failed`

### PR DESCRIPTION
**Pull request by shouc**
fix #102

### CODE REVIEW

**Comment by iVoider** [comment]
I tried this and seems that memory limit lowers corpus items complexity too much. 
Fuzzer now only generates primitive mutations of 1-2 elements, (btw  is it normal behavior for fuzzer to add only Flashloan oracle transactions to the seed? like several token borrows).

**Comment by shouc** [comment]
yeah it is normal

**Comment by iVoider** [comment]
> yeah it is normal. If i increase the memory limit to 1MB the tool would OOM

But there is no sense to fuzz with this branch then. 
Compare some contract generated corpus elements with this one and main branch.
Maybe limiting bytes arrays would be sufficient?

**Comment by shouc** [comment]
the issue here is not due to large bytes arrays. It is actually one contract doing something like this:

```
calldatacopy(71236619313044, 0, 32)
```

which enlarges the memory of EVM to be 71236619313044 + 32

Commonly, this can be resolved by gas constraints but in our cases, we give infinite gas for each call

**Comment by iVoider** [comment]
> the issue here is not due to large bytes arrays. It is actually one contract doing something like this:
> 
> ```
> calldatacopy(71236619313044, 0, 32)
> ```
> 
> which enlarges the memory of EVM to be 71236619313044 + 32
> 
> Commonly, this can be resolved by gas constraints but in our cases, we give infinite gas for each call

How about hooking calldatacopy instr implementation in revm, and throw OutOfGas if value is too big?

**Pull request closed without merging**
