### PR TITLE
Feat fix abi bytes

### PR DESCRIPTION
**Pull request by Kenun99**
ityfuzz uses dynamic bytes for the `bytes1` to `bytes32` variables which however are defined static ones in Solidity document. 
The committed file, i.e., [tests/abi-test/test.sol](https://github.com/fuzzland/ityfuzz/compare/master...Kenun99:feat-fix_abi_bytes?expand=1#diff-2ea998384831ec783939f4c13b3ab038d6cf27b6380310eb41d80ce6386334f4) shows that the current ityfuzz falls in a dead loop when generating random data for the `bytes2` parameter. 

By applying the attached patch, ityfuzz can eventually pass the integration test, i.e., `python3 integration_test.py`.

### CODE REVIEW

**Comment by ByteSecurity** [comment]
我看看

**Review by ByteSecurity — APPROVED** [review]
thx ~

**Comment by ByteSecurity** [comment]
老哥有兴趣加入我们一起完善 ityfuzz 吗 ：）

**Comment by Kenun99** [comment]
> 老哥有兴趣加入我们一起完善 ityfuzz 吗 ：）

谢谢 还有机会的话我会提交PR的

**Comment by ByteSecurity** [comment]
> > 老哥有兴趣加入我们一起完善 ityfuzz 吗 ：）
> 
> 谢谢 还有机会的话我会提交PR的

欢迎加入我们团队一起完善ityfuzz， 远程工作，待遇从优~
详情请联系：
https://t.me/xforce_fuzzland

**Pull request merged**
